TeamBoard/Models/Project.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;

namespace TeamBoard.Models
{
    public class Project
    {
        [NotMapped]
        public static readonly string[] DefaultLabelStyles = new string[] 
        { 
            "btn-default", "btn-primary", "btn-success", 
            "btn-info", "btn-warning", "btn-danger"
        };

        public Project()
        {
            Conferences = new List<Conference>();
            Participations = new List<Participation>();
            Labels = new List<Label>();

            //foreach (var style in DefaultLabelStyles)
            //{
            //    Labels.Add(new Label
            //        {
            //            Style = style,
            //            Header = "",
            //            Project = this
            //        });
            //}
        }

        [Key]
        [Column]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { set; get; }

        [Column]
        [Required]
        [DataType(DataType.Text)]
        [Display(Name="Project name")]
        public string Name { set; get; }

        [Column]
        [DataType(DataType.MultilineText)]
        [Display(Name = "Description")]
        public string Description { set; get; }

        [Column]
        [DataType(DataType.Date)]
        [Display(Name = "Creation date")]
        public DateTime? Date { set; get; }

        [Column]
        [ForeignKey("Author")]
        public string AuthorId { set; get; }

        public virtual ApplicationUser Author { set; get; }

        public virtual Kanban Kanban { get; set; }

        public virtual Bugtracker Bugtracker { set; get; }

        public virtual List<Conference> Conferences { set; get; }

        public virtual List<Participation> Participations { set; get; }

        public virtual ICollection<Label> Labels { get; set; }
    }
}

TeamBoard/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using TeamBoard.Models;

namespace TeamBoard.Controllers
{
    [Authorize]
    public class ProjectsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();


        public ActionResult Index()
        {
            // Отображаем только проекты, в которых данный пользователь участвует или является автором.
            var projects = db.Projects.Where(project =>
                    project.Participations
                        .Any(participant => participant.User.UserName == User.Identity.Name)
                    || project.Author.UserName == User.Identity.Name).ToList();
            return View(projects);
        }

        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.FirstOrDefault(x=> x.Id == id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        [Authorize]
        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Project project)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser currentUser = db.Users.First(user => user.UserName == User.Identity.Name);
                project.AuthorId = currentUser.Id;
                project.Date = DateTime.Now;
                // Добавляем текущего пользователя в участников проекта.
                db.Participations.Add(new Participation { ProjectId = project.Id, UserId = currentUser.Id });

                db.Projects.Add(project);
                db.SaveChanges();

                var currentProject = db.Projects.First(pr => pr.Id == project.Id);

                // Добавляем багтрекер и канбан, привязанные к данному проекту.
                db.Bugtrackers.Add(new Bugtracker { Id = project.Id,  Project = currentProject});
                db.Kanbans.Add(new Kanban { Project = currentProject, Id = currentProject.Id });


                db.SaveChanges();

                foreach (var style in Project.DefaultLabelStyles)
                {
                    db.Labels.Add(new Label
                        {
                            Style = style,
                            Header = "",
                            Project = project
                        });
                }

                db.SaveChanges();

                return RedirectToAction("Details", new { id = currentProject.Id });
            }

            return View(project);
        }

        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }

            ViewBag.ProjectName = project.Name;

            // Создаём новый список участников.
            List<ApplicationUser> addedUsers = new List<ApplicationUser>();
            Project pr = db.Projects.First(p => p.Id == id);
            foreach (Participation participation in pr.Participations)
            {
                if (participation.User.UserName != User.Identity.Name)
                    addedUsers.Add(participation.User);
            }

            //List<ApplicationUser> addedTesters = db.Users.Where(user => user.Participations.Any(p => p.IsQA)).ToList();

            //ViewBag.AddedTesters = addedTesters;
            ViewBag.AddedUsers = addedUsers;
            return View(project);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Project project)
        {
            if (ModelState.IsValid)
            {
                db.Projects.First(p => p.Id == project.Id).Name = project.Name;
                db.Projects.First(p => p.Id == project.Id).Description = project.Description;
                db.SaveChanges();
                var idDictionary = new RouteValueDictionary();
                idDictionary.Add("id", project.Id);
                return RedirectToAction("Details", idDictionary);
            }

            // Создаём новый список участников.
            List<ApplicationUser> addedUsers = new List<ApplicationUser>();
            Project pr = db.Projects.First(p => p.Id == project.Id);
            foreach (Participation participation in pr.Participations)
            {
                addedUsers.Add(participation.User);
            }
            List<ApplicationUser> addedTesters = db.Users.Where(user => user.Participations.Any(p => p.IsQA)).ToList();

            ViewBag.ProjectName = project.Name;
            //ViewBag.AddedTesters = addedTesters;
            ViewBag.AddedUsers = addedUsers;
            return View(project);
        }

        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Project project = db.Projects.Find(id);
            db.Kanbans.Remove(project.Kanban);
            db.Bugtrackers.Remove(project.Bugtracker);
            db.Projects.Remove(project);
            var labels = db.Labels.Where(l => l.ProjectId == project.Id);
            db.Labels.RemoveRange(labels);

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [HttpPost]
        public ActionResult RemoveParticipant(string userId, int projectId)
        {
            //Удаляем одного участника.
            db.Participations.Remove(db.Participations.First(p => p.UserId == userId && p.ProjectId == projectId));
            db.SaveChanges();

            // Создаём новый список участников.
            List<ApplicationUser> addedUsers = new List<ApplicationUser>();
            Project project = db.Projects.First(pr => pr.Id == projectId);
            foreach (Participation participation in project.Participations)
            {
                if (participation.User.UserName != User.Identity.Name)
                    addedUsers.Add(participation.User);
            }

            ViewData["AddedUsers"] = addedUsers;
            ViewData["projectId"] = projectId;
            return PartialView("AddedUsersList");
        }

        [HttpPost]
        public ActionResult AddParticipant(int projectId, string inputedName)
        {
            //Создаём одного участника.
            if (db.Users.Count(u => inputedName == u.UserName) > 0)
            {
                ApplicationUser user = db.Users.First(u => inputedName == u.UserName);
                db.Participations.Add(new Participation() { UserId = user.Id, ProjectId = projectId, IsQA = false });
                db.SaveChanges();
            }
            // Создаём новый список участников.
            List<ApplicationUser> addedUsers = new List<ApplicationUser>();
            Project project = db.Projects.First(pr => pr.Id == projectId);
            foreach (Participation participation in project.Participations)
            {
                if (participation.User.UserName != User.Identity.Name)
                    addedUsers.Add(participation.User);
            }

            ViewData["AddedUsers"] = addedUsers;
            ViewData["PossibleUsers"] = new List<ApplicationUser>();
            ViewData["projectId"] = projectId;
            return PartialView("AddParticipantsPartial");
        }

        [HttpPost]
        public ActionResult CreateHelpList(string inputedText, int projectId)
        {
            List<ApplicationUser> users = new List<ApplicationUser>();
            // Если пользователь ничего не ввёл, то подсказки не должно быть.
            if (inputedText != "")
            {
                // Проверка на то, был ли уже добавлен пользователь.
                users = db.Users.Where(x => (x.UserName.Contains(inputedText) || x.Name.Contains(inputedText)) &&
                    x.Participations.Count(participation => participation.ProjectId == projectId) == 0 &&
                    x.UserName != User.Identity.Name).ToList();
            }
            return PartialView("HelpListPartial", users);
        }

        [HttpPost]
        public ActionResult CreateTestersList(string inputedTesterText, int projectId)
        {
            List<ApplicationUser> users = new List<ApplicationUser>();
            // Если пользователь ничего не ввёл, то подсказки не должно быть.
            if (inputedTesterText != "")
            {
                // Проверка на то, является ли пользователь уже тестировщиком.
                users = db.Users.Where(x => (x.UserName.Contains(inputedTesterText) || x.Name.Contains(inputedTesterText)) &&
                    x.Participations.Any(participation => participation.ProjectId == projectId && !participation.IsQA)).ToList();
            }
            return PartialView("TestersHelpListPartial", users);
        }

        [HttpPost]

TeamBoard/Views/Projects/Create.cshtml
@model TeamBoard.Models.Project
@using TeamBoard.Models
@{
    ViewBag.Title = "Create";
}

<h2>Create new project</h2>

<div class="box">
    <div class="box-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.Name, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Description, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-md-2 control-label">
                        @Html.ActionLink("Back to list", "Index", null, new { @class = "btn btn-default" })
                    </div>
                    <div class="col-md-10">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        }

    </div>
</div>

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
            <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
        }

TeamBoard/Views/Projects/Delete.cshtml
@model TeamBoard.Models.Project

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<div class="box">
    <div class="box-body">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="form-horizontal">
                    <h4>Are you sure you want to delete this?</h4>
                    <hr />
                    <div class="form-group">
                        <label class="control-label col-md-2">Project name:</label>
                        <div class="col-md-10">
                            @Html.DisplayFor(model => model.Name)
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-2 control-label">
                            @Html.ActionLink("Back to list", "Index", null, new { @class = "btn btn-default" })
                        </div>
                        <div class="col-md-10">
                            <input type="submit" value="Delete" class="btn btn-danger" />
                        </div>
                    </div>
                </div>
            }
    </div>
</div>

TeamBoard/Views/Projects/Details.cshtml
@model TeamBoard.Models.Project
@using TeamBoard.Models

@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>@Model.Name - TeamBoard</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/jquery-ui")
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    @Scripts.Render("~/bundles/modernizr")

    <link rel="shortcut icon" href="/Pictures/favicon.ico" type="image/x-icon">
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">

        <!-- Main Header -->
        <header class="main-header">

            <!-- Logo -->
            <a href="@Url.Action("Index", "Projects", null)" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><i class="fa fa-angle-left"></i></span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><i class="fa fa-angle-left"></i> Back to projects</span>
            </a>

            <!-- Header Navbar -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <span class="header-title">
                    @Model.Name
                </span>
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- Control Sidebar Toggle Button -->
                        <li onclick='document.getElementById("openSidebarButton").click()'>
                            <a href="#" data-toggle="control-sidebar"><i class="fa fa-envelope"></i></a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">

            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">

                <!-- Sidebar Menu -->
                <ul class="sidebar-menu">
                    <!-- Optionally, you can add icons to the links -->
                    <li><a href="@Url.Action("Edit", "Projects", new { id = Model.Id })"><i class="fa fa-edit"></i> <span>Edit project</span></a></li>
                    <li><a href="@Url.Action("ShowConference", "Conference")"><i class="fa fa-comment"></i> <span>Conferences</span></a></li>
                    <li><a href="@Url.Action("AddConference", "Conference", new { projectId = Model.Id })"><i class="fa fa-plus"></i> <span>Add conference</span></a></li>
                    <li><a href="@Url.Action("ShowBugtracker", "Bugs", new { id = Model.Bugtracker.Id })"><i class="fa fa-bug"></i> <span>Bugtracker</span></a></li>
                    <li><a href="" type="button" data-toggle="modal" data-target="#Participants"><i class="fa fa-users"></i> <span>Participants</span></a></li>
                </ul><!-- /.sidebar-menu -->
            </section>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header"></section>

            <!-- Main content -->
            <section class="content">
                @Html.Action("Index", "Kanban", Model.Id)
                <!-- Your Page Content Here -->

            </section><!-- /.content -->
        </div><!-- /.content-wrapper -->
        <!-- Main Footer -->
        <footer class="main-footer">
            <!-- To the right -->
            <div class="pull-right hidden-xs">
                Anything you want
            </div>
            <!-- Default to the left -->
            <strong>Copyright &copy; 2015 <a href="#">Company</a>.</strong> All rights reserved.
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark"></aside><!-- /.control-sidebar -->
        <!-- Add the sidebar's background. This div must be placed
                immediately after the control sidebar -->
        <div id="conferences-sidebar" class="control-sidebar-bg" style="overflow-y:auto">

        </div>
    </div><!-- ./wrapper -->

    <!-- Modal -->
    <div class="modal fade" id="Participants" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" style="width:300px;" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    @foreach (var p in Model.Participations)
                    {
                        <h4><a href="@Url.Action("ShowProfile", "Manage", new { id = p.UserId })">@p.User.Name</a></h4>
                    }
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default btn-flat" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>


    
    @using (Ajax.BeginForm("ShowConference", "Conference", new { minimized = Model.Id, id = -1 }, new AjaxOptions { UpdateTargetId = "conferences-sidebar", OnSuccess = "enableConf" }, new { style = "visibility:hidden", @class = "hidden" }))
    {
        <button class="hidden" name="submit" id="openSidebarButton">Open tab</button>
    }
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/jquery.signalR-2.2.0.min.js"></script>
    <script src="~/signalr/hubs"></script>
    <script src="~/Scripts/Custom Scripts/conference-minimized.js"></script>    
    @*Don't remove this script block.*@
    <script type="text/javascript">
        var ADD_COLUMN_ROUTE = "@Url.Action("AddColumn", "Kanban")";
        var DELETE_COLUMN_ROUTE = "@Url.Action("DeleteColumn", "Kanban")";
        var RENAME_COLUMN_ROUTE = "@Url.Action("RenameColumn", "Kanban")";
        var REPLACE_COLUMN_ROUTE = "@Url.Action("ReplaceColumn", "Kanban")";

        var ADD_SUBPARTITION_ROUTE = "@Url.Action("AddSubpartition", "Kanban")";
        var DELETE_SUBPARTITION_ROUTE = "@Url.Action("DeleteSubpartition", "Kanban")";
        var RENAME_SUBPARTITION_ROUTE = "@Url.Action("RenameSubpartition", "Kanban")";
        var REPLACE_SUBCOLUMN_ROUTE = "@Url.Action("ReplaceSubpartition", "Kanban")";

        var ADD_STICKER_ROUTE = "@Url.Action("AddSticker", "Kanban")";
        var DELETE_STICKER_ROUTE = "@Url.Action("DeleteSticker", "Kanban")";
        var GET_STICKER_INFO_ROUTE = "@Url.Action("GetStickerInfo", "Kanban")";
        var SET_STICKER_DESCRIPTION_ROUTE = "@Url.Action("SetStickerDescription", "Kanban")";
        var RENAME_STICKER_ROUTE = "@Url.Action("RenameSticker", "Kanban")";
        var REPLACE_STICKER_ROUTE = "@Url.Action("ReplaceSticker", "Kanban")";
        var SET_EXECUTING_STICKER_ROUTE = "@Url.Action("SetStickerTaskExecuting", "Kanban")";
        var SET_STICKER_LABEL_ROUTE = "@Url.Action("SetStickerLabel", "Kanban")";

        var DOWNLOAD_MESSAGES_ROUTE = "@Url.Action("DownloadMessages", "Conference")";

        $(document).ready(function () {
            $("#kanban").css(
                "min-height", 
                $(document).height() 
                - $(".navbar.navbar-static-top").outerHeight(true) 
                - $(".main-footer").outerHeight(true));
        });

    </script>

    <script type="text/javascript" src="~/Scripts/Custom Scripts/kanban.js"></script>
    <script type="text/javascript" src="~/Scripts/Custom Scripts/app.js"></script>
</body>
</html>



@*<h2>@ViewBag.ProjectName</h2>

<div>
    <h4>Project</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Author")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    <div>
        @Html.Action("Index", "Kanban", Model.Id)
    </div>

    @Html.ActionLink("Show bugtracker", "ShowBugtracker", "Bugs", new { id = Model.Bugtracker.Id }, null)
    <br />
    @Html.ActionLink("Add Conference", "AddConference", "Conference", new { projectId = Model.Id }, null)
</div>
<p>
    @if (User.Identity.IsAuthenticated && User.Identity.Name == Model.Author.UserName)
    {
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) <b>|</b>
    }
    @Html.ActionLink("Back to List", "Index")
</p>*@

TeamBoard/Views/Projects/Edit.cshtml
@model TeamBoard.Models.Project
@using TeamBoard.Models

@{
    ViewBag.Title = "Edit";

    List<ApplicationUser> addedUsers = ViewBag.AddedUsers;
    //List<ApplicationUser> addedTesters = ViewBag.AddedTesters;

    ViewDataDictionary dictionary = new ViewDataDictionary();
    dictionary.Add("AddedUsers", addedUsers);
    dictionary.Add("PossibleUsers", new List<ApplicationUser>());
    //dictionary.Add("AddedTesters", addedTesters);
    //dictionary.Add("PossibleTesters", new List<ApplicationUser>());
    dictionary.Add("projectId", Model.Id);
}

<h2>@ViewBag.ProjectName</h2>

<div class="box">
    <div class="box-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="col-md-6">
                <h4>Edit project</h4>
                <hr />
                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, "Name", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Description, "Description", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-2 control-label">
                            @Html.ActionLink("Back to list", "Index", null, new { @class = "btn btn-default" })
                        </div>
                        <div class="col-md-10">
                            <input type="submit" value="Save" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
            </div>
        }

        <div id="Participants" class="col-md-6">
            @Html.Partial("AddParticipantsPartial", dictionary)
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
}

TeamBoard/Views/Projects/Index.cshtml
@model IEnumerable<TeamBoard.Models.Project>

@{
    ViewBag.Title = "Projects";
}
<h2>
Your projects
@if (User.Identity.IsAuthenticated)
            {
    <span>
        <small>
            @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary btn-xs" })
        </small>
    </span>
}
</h2>
<div class="box">
    <div class="box-body">
        @if (Model.Count() > 0)
        {
            foreach (var item in Model)
            {
                <h3>@Html.ActionLink(item.Name, "Details", new { id = item.Id })
                    <small>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-primary btn-xs" })
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger btn-xs" })
                    </small>
                    <span class="pull-right">
                        <small>
                            @item.Date
                        </small>
                    </span>
                </h3>
                <p>
                    @item.Description
                </p>
                <p>
                    By @item.Author.Name
                    <span class="pull-right">
                        @Html.ActionLink("Go to bugtracker", "ShowBugtracker", "Bugs", new { id = item.Id }, new { @class = "btn btn-default btn-sm" })
                        @Html.ActionLink("Go to project", "Details", new { id = item.Id }, new { @class = "btn btn-primary btn-sm" })
                    </span>
                </p>
                <hr />
            }
        }
        else
        {
            <h2>
                Ooops! There are no projects yet :( &nbsp;&nbsp;@Html.ActionLink("Create?", "Create", null, null)
            </h2>
        }
    </div>
</div>